---
title: "Salus Combos"
author: "Jill Deines"
date: "November 5, 2017"
output: 
  html_document:
    toc: yes
---

Goal: Create SALUS experiment combinations: unique soil-climate-crop-irrigation combos

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, fig.path='figure/02.20_salus_combos/',
                      cache = TRUE)
```

**R Packages Needed**

```{r packages, warning=FALSE, message=FALSE}
library(tidyverse)
library(sf)
```

# directory parameters

```{r directories}
soilDir <- 'C:/Users/deinesji/Dropbox/1PhdJill/hpa/LEMAs/data/soil'
soilName <- 'ssurgo_gmd4p_wgs84'

cdlDir <- 'C:/Users/deinesji/Google Drive/GEE_AIM-RRB/GEE_LEMA/cdl_vectors_lema'
cdlName <- '2015_CDL_gmd4PlusClips_vector60.geojson'
```


# test load soil export

```{r loadsoil}
mukeys <- st_read(paste0(soilDir,'/',soilName,'.shp'))
nrow(mukeys)
length(unique(mukeys$MUKEY))
```

455 unique soil types 

# load test cdl

```{r loadcdl}
cdltest <- st_read(paste0(cdlDir,'/',cdlName))
nrow(cdltest)
length(unique(cdltest$class))
```

31 unique crop classes in 2015